### ISSUE TITLE
更改个人主页背景图片的卡片有bug

### ISSUE THREAD

**Issue by Ducklyqwq** [d0j1a1701/argon-luogu#23]
更改个人主页背景图片的卡片是白色且会被亚克力效果遮住（如下图）
![image](https://github.com/user-attachments/assets/6256b4f0-faa0-404f-92d8-d88eb0d50241)

**Comment by songxingling1** [comment]
fixed，请使用develop分支的预览版

**Comment by Ducklyqwq** [comment]
> fixed，请使用develop分支的预览版

thanks
