### ISSUE TITLE
题解界面左侧导航栏未适配完全

### ISSUE THREAD

**Issue by Ducklyqwq** [d0j1a1701/argon-luogu#25]
rt，导航栏展开后向下滑动会有部分空白
![image](https://github.com/user-attachments/assets/de4a4ca9-c8c9-4fd4-a4fb-7d3274794ec9)

**Comment by songxingling1** [comment]
抱歉，这个问题在我的电脑上无法复现

**Comment by songxingling1** [comment]
请问你用的是什么浏览器呢？

**Comment by Ducklyqwq** [comment]
> 请问你用的是什么浏览器呢？

Microsoft Edge 128.0.2739.42, Windows 11 系统

**Comment by songxingling1** [comment]
> > 请问你用的是什么浏览器呢？
> 
> Microsoft Edge 128.0.2739.42, Windows 11 系统

请尝试使用最新版Edge浏览器，升级至最新版浏览器可能可以解决此问题。
![image](https://github.com/user-attachments/assets/97b7aac1-0b00-4a13-8bb7-bf866cf59c91)

**Comment by songxingling1** [comment]
已成功复现

**Comment by songxingling1** [comment]
fixed感谢贡献
