### ISSUE TITLE
提个意见？

### ISSUE THREAD

**Issue by songxingling1** [d0j1a1701/argon-luogu#27]
可不可以提一个意见？哪里还需要改进？ @d0j1a1701

**Comment by d0j1a1701** [comment]
很不错啦，不过硬要提的话....

1. 加载新页面时的 Header 动画最好快一点，晃眼睛
2. 加一个控制动画开关的选项照顾垃圾电脑
3. 那个“隐藏讨论区「编辑回复­」栏”的选项会把 Markdown 编辑器一起吃掉（好像是我当初写的 bug
4. Markdown 编辑器代码高亮看不清

![image](https://github.com/user-attachments/assets/4a8e848a-ffcf-4444-9302-37cb6de1ff7c)

**Comment by songxingling1** [comment]
1. fixed
2. fixed
3. 不知道最后的结果长什么样所以不知道怎么实现
4. fixed

**Comment by d0j1a1701** [comment]
第三条的意思是只隐藏编辑回复的按钮，但页面滚下去还是能用 Markdown 编辑器。现在的错误实现是隐藏按钮的同时把 Markdown 编辑器给吞了，页面滚下去也没有。

**Comment by songxingling1** [comment]
fixed
