### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by goblock2021** [d0j1a1701/argon-luogu#3]
1.讨论区左侧板块链接太黑了看不清
![image](https://github.com/d0j1a1701/argon-luogu/assets/114788565/dbb8db3f-ee15-416c-b4bc-05b9f69b7925)

2.为啥我的exlg不能正常美化...

3.左侧时不时出现诡异透明条
![image](https://github.com/d0j1a1701/argon-luogu/assets/114788565/dac44e1b-f0f0-48d3-80a6-dc09baf33347)

**Comment by d0j1a1701** [comment]
问题一已解决

问题二无法复现

问题三似乎是浏览器对 `backdrop-filter` 的实现问题，难以复现，无法解决

**Comment by d0j1a1701** [comment]
已成功复现问题三：打开主页，将鼠标悬停至任意超链接即可复现

**Comment by songxingling1** [comment]
问题三似乎就是因为浏览器对 `backdrop-filter` 的实现的问题，因为我通过关闭这个样式发现问题三不存在了，并且如果我换一个浏览器，那么问题三就会消失，所以这个问题是浏览器的问题，So无法解决:(
