### ISSUE TITLE
代码块高亮疑似bug？

### ISSUE THREAD

**Issue by xnull666** [d0j1a1701/argon-luogu#4]
![image](https://github.com/user-attachments/assets/4a1f1050-0570-45fa-af43-8176fed4de60)
![image](https://github.com/user-attachments/assets/7a4c01cc-38dd-4173-a6fe-361071eb5095)
求助

**Comment by caotianlang** [comment]
我也遇到了相同的问题, 同求 /kel/kel/kel

**Comment by caotianlang** [comment]
把插件卸载后重装之后就莫名其妙的好了

**Comment by xnull666** [comment]
感谢，试一下

**Comment by xnull666** [comment]
感谢，试一下
