### ISSUE TITLE
关于题解界面

### ISSUE THREAD

**Issue by JackyLu0520** [d0j1a1701/argon-luogu#6]
题解也使用了新的界面，但是没有适配
![image](https://github.com/user-attachments/assets/a9c29450-4f3c-4f55-b8bf-e1f4922286cb)

**Comment by songxingling1** [comment]
Cu ball

**Comment by JackyLu0520** [comment]
咕值和等级分界面也有这个问题，不过我发现把洛谷专栏编辑部分的正则改一下就行了(?)
![image](https://github.com/user-attachments/assets/7ac4f0f7-579c-4693-9057-c2f128a810b1)
![image](https://github.com/user-attachments/assets/be1987a5-b057-4405-8bed-cf9f68b116bd)
![image](https://github.com/user-attachments/assets/792c779d-4766-492a-9f0a-22975963e639)

**Comment by songxingling1** [comment]
楼上正解%%%（我试了，可以，也许可以提个Pull request）
